# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poke',
            field=models.IntegerField(max_length=45),
        ),
        migrations.AlterField(
            model_name='poke',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Poke.User'),
        ),
    ]
