# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poke', '0002_auto_20170201_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poke',
            field=models.IntegerField(),
        ),
    ]
